name: CrazyAuctions
authors:
  - BadBones69
  - AMinecraftDev
main: me.badbones69.crazyauctions.Main
version: ${version}${build.number}
depend:
  - Vault
  - MassiveCore
api-version: 1.13
description: A plugin to auction off items globally.
commands:
  ca:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, crazyauctions, ah, hdv]